project 'QueryHandler.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift

use_frameworks!
#link_with 'CrowdZen'

target 'QueryHandler' do
pod 'Alamofire', '~> 4.0'
pod 'thrift', '0.9.3'
pod 'Sodium', '0.3'
end

post_install do |installer|	

  installer.pods_project.targets.each do |target|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end

    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

